UE5_PROFILE = {
    "pelvis": "pelvis",
    "spine_01": "spine_01",
    "spine_02": "spine_02",
    "spine_03": "spine_03",
    "neck_01": "neck_01",
    "neck_02": "neck_02",
    "head": "head",
    "clavicle_l": "clavicle_l",
    "clavicle_pec_l": "clavicle_pec_l",
    "upperarm_l": "upperarm_l",
    "lowerarm_l": "lowerarm_l",
    "hand_l": "hand_l",
    "pinky_metacarpal_l": "pinky_metacarpal_l",
    "ring_metacarpal_l": "ring_metacarpal_l",
    "middle_metacarpal_l": "middle_metacarpal_l",
    "index_metacarpal_l": "index_metacarpal_l",
    "pinky_01_l": "pinky_01_l",
    "pinky_02_l": "pinky_02_l",
    "pinky_03_l": "pinky_03_l",
    "ring_01_l": "ring_01_l",
    "ring_02_l": "ring_02_l",
    "ring_03_l": "ring_03_l",
    "middle_01_l": "middle_01_l",
    "middle_02_l": "middle_02_l",
    "middle_03_l": "middle_03_l",
    "index_01_l": "index_01_l",
    "index_02_l": "index_02_l",
    "index_03_l": "index_03_l",
    "thumb_01_l": "thumb_01_l",
    "thumb_02_l": "thumb_02_l",
    "thumb_03_l": "thumb_03_l",
    "clavicle_r": "clavicle_r",
    "clavicle_pec_r": "clavicle_pec_r",
    "upperarm_r": "upperarm_r",
    "lowerarm_r": "lowerarm_r",
    "hand_r": "hand_r",
    "pinky_metacarpal_r": "pinky_metacarpal_r",
    "ring_metacarpal_r": "ring_metacarpal_r",
    "middle_metacarpal_r": "middle_metacarpal_r",
    "index_metacarpal_r": "index_metacarpal_r",
    "pinky_01_r": "pinky_01_r",
    "pinky_02_r": "pinky_02_r",
    "pinky_03_r": "pinky_03_r",
    "ring_01_r": "ring_01_r",
    "ring_02_r": "ring_02_r",
    "ring_03_r": "ring_03_r",
    "middle_01_r": "middle_01_r",
    "middle_02_r": "middle_02_r",
    "middle_03_r": "middle_03_r",
    "index_01_r": "index_01_r",
    "index_02_r": "index_02_r",
    "index_03_r": "index_03_r",
    "thumb_01_r": "thumb_01_r",
    "thumb_02_r": "thumb_02_r",
    "thumb_03_r": "thumb_03_r",
    "thigh_l": "thigh_l",
    "calf_l": "calf_l",
    "foot_l": "foot_l",
    "ankle_bck_l": "ankl_bck_l",
    "ball_l": "ball_l",
    "thigh_r": "thigh_r",
    "calf_r": "calf_r",
    "foot_r": "foot_r",
    "ankle_bck_r": "ankl_bck_r",
    "ball_r": "ball_r",
}

PSK_PROFILE = {
    "pelvis": "pelvis",
    "spine_01": "spine_01",
    "spine_02": "spine_02",
    "spine_03": "spine_03",
    "clavicle_l": "clavicle_l",
    "upperarm_l": "upperarm_l",
    "lowerarm_l": "lowerarm_l",
    "hand_l": "hand_l",
    "neck_01": "neck_01",
    "head": "head",
    "thigh_l": "thigh_l",
    "calf_l": "calf_l",
    "foot_l": "foot_l",
    "ball_l": "ball_l",
    "thigh_r": "thigh_r",
    "calf_r": "calf_r",
    "foot_r": "foot_r",
    "ball_r": "ball_r",
}

BLENDER_METARIG_PROFILE = {
    "pelvis": "pelvis",
    "spine.01": "spine.01",
    "spine.02": "spine.02",
    "spine.03": "spine.03",
    "neck.01": "neck.01",
    "neck.02": "neck.02",
    "face": "face",

    "shoulder.L": "shoulder.L",
    "upperarm.L": "upperarm.L",
    "lowerarm.L": "lowerarm.L",
    "hand.L": "hand.L",
    "palm.L": "palm.L",
    "finger.L": "finger.L",

    "shoulder.R": "shoulder.R",
    "upperarm.R": "upperarm.R",
    "lowerarm.R": "lowerarm.R",
    "hand.R": "hand.R",
    "palm.R": "palm.R",
    "finger.R": "finger.R",
    
    "thigh.L": "thigh.L",
    "calf.L": "calf.L",
    "foot.L": "foot.L",
    "ball.L": "ball.L",

    "thigh.R": "thigh.R",
    "calf.R": "calf.R",
    "foot.R": "foot.R",
    "ball.R": "ball.R",
}

PROFILES = {
    "UE5": UE5_PROFILE,
    "PSK": PSK_PROFILE,
    "BLENDER_METARIG": BLENDER_METARIG_PROFILE,
}
